config/routes.rb
Rails.application.routes.draw do
  root to: 'static_pages#home' # app/views/static_pages/home.html.erbの内容がトップページに表示
  get    'signup', to: 'users#new'
  get    'login' , to: 'sessions#new'
  post   'login' , to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  
  get     '/users/:id/followings', to: 'users#followings', as: :followings_user
  get     '/users/:id/followers', to: 'users#followers', as: :followers_user
  
  resources :users
  resources :microposts
  resources :relationships, only: [:create, :destroy]
end

app/models/user.rb
class User < ActiveRecord::Base
    before_save { self.email = self.email.downcase }

    validates :name, presence: true, length: { maximum: 50 }

    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
    validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }

    has_secure_password
    has_many :microposts

# あるユーザーがフォローしている人の集まり
  has_many :following_relationships, class_name:  "Relationship",
                                     foreign_key: "follower_id",
                                     dependent:   :destroy
  has_many :following_users, through: :following_relationships, source: :followed
# あるユーザをフォーローしている人の集まり
  has_many :follower_relationships, class_name:  "Relationship",
                                    foreign_key: "followed_id",
                                    dependent:   :destroy
  has_many :follower_users, through: :follower_relationships, source: :follower
# 他のユーザーをフォローする
  def follow(other_user)
    following_relationships.find_or_create_by(followed_id: other_user.id)
  end

# フォローしているユーザーをアンフォローする
  def unfollow(other_user)
    following_relationship = following_relationships.find_by(followed_id: other_user.id)
    following_relationship.destroy if following_relationship
  end

# あるユーザーをフォローしているかどうか？
  def following?(other_user)
    following_users.include?(other_user)
  end
  
# 自分とフォローしているユーザのつぶやきを取得するメソッド
  def feed_items
    Micropost.where(user_id: following_user_ids + [self.id])
    # following_user_ids:has_many :following_users(18行目)で自動的に生成されたメソッド
    # フォローしているユーザのIDを配列で返す。
    # 配列同士は、+ で要素を足し合わせることができる。
    
    # self.id:selfは、どのユーザがこのコードを実行しようとしているかで変わります。
    # user1.feed_itemsの場合、self=user1となります。
    
    # Microposts:モデル名
    # .where(user_id: ):select microposts.* from micropost where microposts.user_id = ???
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :check_session, only: [:edit, :update]
  before_action :set_user, only: [:edit, :update]
#  before_action :followings, only: [:show]
#  before_action :followers, only: [:show]

  def show
    # ブラウザから指定された:idに関するインスタンスを作成し、
    # UsersControllerのインスタンス変数に代入
    @user = User.find(params[:id])
    # ユーザに紐ついたmicropostsテーブルを作成日時が新しい順に並び替え
    # select "microposts".* from "microposts" order by created_at DESC
    # userControllerのインスタンス変数に代入
    @microposts = @user.microposts.order(created_at: :desc)
  end

  def new
    # Userクラス(model)のインスタンスを作成し、
    # UsersControllerのインスタンス変数に代入
    @user = User.new
  end
  
  def create
    # 送信されたパラメータの内容を
    # 新しいUsersControllerのインスタンス変数に代入
    @user = User.new(user_params)
    if @user.save
      # フラッシュメッセージの表示
      flash[:success] = "Welcome to the Sample App!!"
      # user_path(@user)と同義。詳細画面（show）にリダイレクト
      redirect_to @user
    else
      render 'new'
    end
  end
  
  # # # #
  def edit
  end

  def update
    if @user.update(user_params)
      # 保存に成功した場合はプロファイルページへリダイレクト
      redirect_to user_path , notice: '基本情報を編集しました'
    else
      # 保存に失敗した場合は編集画面へ戻す
      render 'edit'
    end
  end
  # # # #

  def followings
    # ブラウザから指定された:idに関するインスタンスを作成し、
    # UsersControllerのインスタンス変数に代入
    @user = User.find(params[:id])
    # ユーザに紐ついたfollowing_usersテーブルを
    # userControllerのインスタンス変数に代入
    # userControllerのインスタンス変数に代入
    @followings = @user.following_users.all
    
  end
  
  def followers
    # ブラウザから指定された:idに関するインスタンスを作成し、
    # UsersControllerのインスタンス変数に代入
    @user = User.find(params[:id])
    # ユーザに紐ついたfollowing_usersテーブルを
    # userControllerのインスタンス変数に代入
    @followers = @user.follower_users.all
  end


  private

  # ストロングパラメータで、has_secure_passwordで提供された
  # データベースにない属性を指定しているのに注意。
  # password,password_confirmation
  def user_params
    params.require(:user).permit(:name, :email, :password,
                                 :password_confirmation,:country)
  end

  def set_user
    @user = User.find(params[:id])
  end
  
  def check_session
    @user = User.find(params[:id])
    if current_user != @user
      redirect_to root_path , notice: '編集と更新を禁止しています'
    else
    end
  end
  
end

app/helpers/users_helper.rb
module UsersHelper
  def gravatar_for(user, options = { size: 80 })
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
end

app/views/users/_follow.html.erb
<%= form_for(current_user.following_relationships.build, remote: true) do |f| %>
    <div><%= hidden_field_tag :followed_id, @user.id %></div>
    <%= f.submit "Follow", class: "btn btn-primary" %>
<% end %>

app/views/users/_follow_form.html.erb
<% if current_user != @user %>
    <div id="follow_form">
        <% if  current_user.following?(@user) %>
            <%= render 'unfollow' %>
        <% else %>
            <%= render 'follow' %>
        <% end %>
    </div>
<% end %>

app/views/users/_form.html.erb
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user) do |f| %>
        <%= render 'shared/error_messages', object: f.object %> <!-- ここを追加 -->

        <%= f.label :name %>
        <%= f.text_field :name, :class =>"form-control" %>
    
        <%= f.label :email %>
        <%= f.text_field :email, :class =>"form-control"  %>
    
        <%= f.label :password %>
        <%= f.password_field :password, :class =>"form-control"  %>
    
        <%= f.label :password_confirmation, "Confirmation" %>
        <%= f.password_field :password_confirmation, :class =>"form-control"  %>
        
        <%= f.label :country %>
        <%= f.text_field :country, :class =>"form-control"  %>

        <%= f.submit class: "btn btn-large btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/_unfollow.html.erb
<%= form_for(current_user.following_relationships.find_by(followed_id: @user.id),
            html: { method: :delete },
            remote: true) do |f| %>
    <div><%= hidden_field_tag :folowed_id, @user.id %></div>
    <%= f.submit "Unfollow", class: "btn" %>
<% end %>

app/views/users/edit.html.erb
<h1>Sign up</h1>

<%= render 'form' %>

app/views/users/followers.html.erb
<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
      <h1>
        <%= gravatar_for @user %>
        <%= @user.name %>
      </h1>
    </section>
  </aside>
  <div class="col-md-8">
    <ul class="nav nav-pills nav-justified">
      <li role="presentation"><%= link_to "profile", user_path(@user) %></li>
      <li role="presentation"><%= link_to "Following", followings_user_path(@user) %></li>
      <li role="presentation" class="active"><%= link_to "Follower", followers_user_path(@user) %></li>
    </ul>
    <% if @user.follower_users.any? %>
      <h3>Follower User (<%= @user.follower_users.count %>)</h3>
        <ol class="follow">
        <% @followers.each do |follower| %>
            <li>
                <span class="user"><%= link_to follower.name, user_path(follower) %></sapn>
                <span class="user"><%= follower.email %></span>
            </li>
        <% end %>
        </ol>
    <% end %>
  </div>
</div>

app/views/users/followings.html.erb
<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
      <h1>
        <%= gravatar_for @user %>
        <%= @user.name %>
      </h1>
    </section>
  </aside>
  <div class="col-md-8">
    <ul class="nav nav-pills nav-justified">
      <li role="presentation"><%= link_to "profile", user_path(@user) %></li>
      <li role="presentation" class="active"><%= link_to "Following", followings_user_path(@user) %></li>
      <li role="presentation"><%= link_to "Follower", followers_user_path(@user) %></li>
    </ul>
    <% if @user.following_users.any? %>
      <h3>Follower User (<%= @user.following_users.count %>)</h3>
        <ol class="follow">
        <% @followings.each do |following| %>
            <li>
                <span class="user"><%= link_to following.name, user_path(following) %></sapn>
                <span class="user"><%= following.email %></span>
            </li>
        <% end %>
        </ol>
    <% end %>
  </div>
</div>

app/views/users/form.html.erb
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user) do |f| %>
        <%= render 'shared/error_messages', object: f.object %> <!-- ここを追加 -->

        <%= f.label :name %>
        <%= f.text_field :name, :class =>"form-control" %>
    
        <%= f.label :email %>
        <%= f.text_field :email, :class =>"form-control"  %>
    
        <%= f.label :password %>
        <%= f.password_field :password, :class =>"form-control"  %>
    
        <%= f.label :password_confirmation, "Confirmation" %>
        <%= f.password_field :password_confirmation, :class =>"form-control"  %>
        
        <%= f.label :country %>
        <%= f.text_field :country, :class =>"form-control"  %>

        <%= f.submit class: "btn btn-large btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/new.html.erb
<h1>Sign up</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user) do |f| %>
        <%= render 'shared/error_messages', object: f.object %> <!-- ここを追加 -->

        <%= f.label :name %>
        <%= f.text_field :name, :class =>"form-control" %>
    
        <%= f.label :email %>
        <%= f.text_field :email, :class =>"form-control"  %>
    
        <%= f.label :password %>
        <%= f.password_field :password, :class =>"form-control"  %>
    
        <%= f.label :password_confirmation, "Confirmation" %>
        <%= f.password_field :password_confirmation, :class =>"form-control"  %>

        <%= f.submit "Create my account", class: "btn btn-large btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
      <h1>
        <%= gravatar_for @user %>
        <%= @user.name %>
      </h1>
    </section>
  </aside>
  <div class="col-md-8">
    <ul class="nav nav-pills nav-justified">
      <li role="presentation" class="active"><%= link_to "profile", user_path(@user) %></li>
      <li role="presentation"><%= link_to "Following", followings_user_path(@user) %></li>
      <li role="presentation"><%= link_to "Follower", followers_user_path(@user) %></li>
    </ul>
    <%= render 'follow_form' if logged_in? %>
    <% if @user.microposts.any? %>
      <h3>Microposts (<%= @user.microposts.count %>)</h3>
      <ol class="microposts">
        <%= render @microposts %>
      </ol>
    <% end %>
  </div>
</div>